Simple Bedroom Scene: progresscpp::ProgressBar Class Reference
progresscpp::ProgressBar Class Reference
#include <progressbar.hpp>
Public Member Functions
ProgressBar (unsigned int total, unsigned int width, char complete, char incomplete)
ProgressBar (unsigned int total, unsigned int width)
unsigned int operator++ ()
void display () const
void done () const
Private Attributes
unsigned int ticks = 0
const unsigned int total_ticks
const unsigned int bar_width
const char complete_char = '='
const char incomplete_char = ' '
const std::chrono::steady_clock::time_point start_time = std::chrono::steady_clock::now()
Constructor & Destructor Documentation
ProgressBar() [1/2]
progresscpp::ProgressBar::ProgressBar (unsigned int total, unsigned int width, char complete, char incomplete) inline
                                                                                             :
             total_ticks{ total }, bar_width{ width }, complete_char{ complete }, incomplete_char{ incomplete } {}
ProgressBar() [2/2]
progresscpp::ProgressBar::ProgressBar (unsigned int total, unsigned int width) inline
 : total_ticks{ total }, bar_width{ width } {}
Member Function Documentation
display()
void progresscpp::ProgressBar::display () const inline
{
             float progress = (float)ticks / total_ticks;
             int pos = (int)(bar_width * progress);
             std::chrono::steady_clock::time_point now = std::chrono::steady_clock::now();
             auto time_elapsed = std::chrono::duration_cast<std::chrono::milliseconds>(now - start_time).count();
             std::cout << "[";
             for (int i = 0; i < bar_width; ++i) {
                 if (i < pos) std::cout << complete_char;
                 else if (i == pos) std::cout << ">";
                 else std::cout << incomplete_char;
             }
             std::cout << "] " << int(progress * 100.0) << "% "
                 << float(time_elapsed) / 1000.0 << "s\r";
             std::cout.flush();
         }
References bar_width, complete_char, incomplete_char, start_time, ticks, and total_ticks.
Referenced by done(), and main().
done()
void progresscpp::ProgressBar::done () const inline
{
             display();
             std::cout << std::endl;
         }
References display().
Referenced by main().
operator++()
unsigned int progresscpp::ProgressBar::operator++ () inline
 { return ++ticks; }
References ticks.
Member Data Documentation
bar_width
const unsigned int progresscpp::ProgressBar::bar_width private
Referenced by display().
complete_char
const char progresscpp::ProgressBar::complete_char = '=' private
Referenced by display().
incomplete_char
const char progresscpp::ProgressBar::incomplete_char = ' ' private
Referenced by display().
start_time
const std::chrono::steady_clock::time_point progresscpp::ProgressBar::start_time = std::chrono::steady_clock::now() private
Referenced by display().
ticks
unsigned int progresscpp::ProgressBar::ticks = 0 private
Referenced by display(), and operator++().
total_ticks
const unsigned int progresscpp::ProgressBar::total_ticks private
Referenced by display().
The documentation for this class was generated from the following file:
progressbar.hpp